# Generated by Django 5.0.3 on 2024-03-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
